#!/bin/sh

readonly PSQL_DATA_PATH=/var/lib/pgsql/data

sudo cp $1.crt $1.key $PSQL_DATA_PATH/

readonly name=$(basename $1)
readonly key=$PSQL_DATA_PATH/$name.key
sudo chmod 600 $key
sudo chown postgres $key
